### ISSUE TITLE
Can't fresh build repository

### ISSUE THREAD

**Issue by KarelPeeters** [pdvrieze/gradle-codegen#2]
When doing `git clone` and `.\gradlew build`, the build fails with 

```
FAILURE: Build failed with an exception.

* Where:
Build file '...\gradle-codegen\build.gradle' line: 59

* What went wrong:
A problem occurred evaluating root project 'gradle-codegen'.
> Could not get unknown property 'bintrayUser' for object of type com.jfrog.bintray.gradle.BintrayExtension.
```

I'm assuming you have the variables `bintrayUser` and `bintrayApiKey` only in your local gradle files, but that prevents other people from easily building from source.

Maybe it's possible to add a check for this?

**Comment by pdvrieze** [comment]
This should be fixed in 0.5.11 and master. Thanks to @EvanOman

**Comment by EvanOman** [comment]
No problem @pdvrieze , thanks for accepting the rando PR. Cool project!

**Comment by KarelPeeters** [comment]
All working now, thanks both for the quick resolution of my issues!

**Comment by pdvrieze** [comment]
Thanks, I had to write it for the kotlinsql project (I need variants of classes with 1,2,3,.... generic parameters. Kind of tedious to create/maintain by hand.

**Comment by KarelPeeters** [comment]
That would be https://github.com/pdvrieze/kotlinsql/tree/master/src/generators/kotlin/kotlinsql/builder, right? I'm going to have a look trough the source there to find out what the "idiomatic usage" is like.

**Comment by pdvrieze** [comment]
That would be correct. I'm not saying that that project does things optimally, for example you may want to use kotlinpoet instead of outputting manually.
